import { describe, expect, it } from "vitest";
import {
  isAutomatedInbound,
  shouldEnqueueSuggestedReply,
} from "../email-handler";

const eligible = {
  agentAutodraft: 1,
  autoFiledSpam: false,
  modelConfigured: true,
  headers: {},
  senderAddress: "customer@example.com",
};

describe("suggested reply enqueue gates", () => {
  it("enqueues when every gate passes", () => {
    expect(shouldEnqueueSuggestedReply(eligible)).toBe(true);
  });

  it("does not enqueue when per-inbox autodraft is off", () => {
    expect(
      shouldEnqueueSuggestedReply({ ...eligible, agentAutodraft: 0 }),
    ).toBe(false);
  });

  it("does not enqueue auto-junked mail", () => {
    expect(
      shouldEnqueueSuggestedReply({ ...eligible, autoFiledSpam: true }),
    ).toBe(false);
  });

  it("does not enqueue when no model provider is configured", () => {
    expect(
      shouldEnqueueSuggestedReply({ ...eligible, modelConfigured: false }),
    ).toBe(false);
  });

  it.each([
    [{ "Auto-Submitted": "auto-generated" }],
    [{ "Auto-Submitted": "auto-replied" }],
    [{ Precedence: "bulk" }],
    [{ Precedence: "LIST" }],
    [{ Precedence: "junk" }],
    [{ "List-Id": "<newsletter.example.com>" }],
    [{ "List-Unsubscribe": "<mailto:leave@example.com>" }],
    [{ "Return-Path": "  <>  " }],
    [{ "Content-Type": "multipart/report; report-type=delivery-status" }],
    [{ "X-Autoreply": "yes" }],
    [{ "X-Autorespond": "yes" }],
    [{ "X-Auto-Response-Suppress": "All" }],
    [{ "X-Autogenerated": "yes" }],
  ])("does not enqueue automated mail with headers %o", (headers) => {
    expect(isAutomatedInbound(headers, eligible.senderAddress)).toBe(true);
    expect(shouldEnqueueSuggestedReply({ ...eligible, headers })).toBe(false);
  });

  it.each([
    "mailer-daemon@example.com",
    "postmaster+dsn@example.com",
    "noreply@example.com",
    "no-reply+ticket@example.com",
    "do-not-reply@example.com",
  ])("does not enqueue automated sender %s", (senderAddress) => {
    expect(isAutomatedInbound({}, senderAddress)).toBe(true);
    expect(
      shouldEnqueueSuggestedReply({ ...eligible, senderAddress }),
    ).toBe(false);
  });

  it("allows Auto-Submitted: no", () => {
    const headers = { "Auto-Submitted": "no" };
    expect(isAutomatedInbound(headers, eligible.senderAddress)).toBe(false);
    expect(shouldEnqueueSuggestedReply({ ...eligible, headers })).toBe(true);
  });
});
