function headerValue(
  headers: Record<string, string>,
  name: string,
): string | undefined {
  const target = name.toLowerCase();
  for (const [key, value] of Object.entries(headers)) {
    if (key.toLowerCase() === target) return value;
  }
  return undefined;
}

export function isAutomatedInbound(
  headers: Record<string, string>,
  senderAddress?: string,
): boolean {
  const autoSubmitted = headerValue(headers, "auto-submitted");
  if (
    autoSubmitted !== undefined &&
    autoSubmitted.trim().toLowerCase() !== "no"
  ) {
    return true;
  }

  const precedence = headerValue(headers, "precedence")?.trim().toLowerCase();
  if (precedence === "bulk" || precedence === "list" || precedence === "junk") {
    return true;
  }

  if (
    headerValue(headers, "list-id") !== undefined ||
    headerValue(headers, "list-unsubscribe") !== undefined
  ) {
    return true;
  }

  if (headerValue(headers, "return-path")?.trim() === "<>") {
    return true;
  }

  const contentType = headerValue(headers, "content-type")
    ?.trim()
    .toLowerCase();
  if (contentType?.startsWith("multipart/report")) {
    return true;
  }

  if (
    headerValue(headers, "x-autoreply") !== undefined ||
    headerValue(headers, "x-autorespond") !== undefined ||
    headerValue(headers, "x-auto-response-suppress") !== undefined ||
    headerValue(headers, "x-autogenerated") !== undefined
  ) {
    return true;
  }

  const localPart = senderAddress
    ?.trim()
    .toLowerCase()
    .split("@", 1)[0]
    ?.split("+", 1)[0];
  return (
    localPart === "mailer-daemon" ||
    localPart === "postmaster" ||
    localPart === "noreply" ||
    localPart === "no-reply" ||
    localPart === "do-not-reply"
  );
}
