/**
 * Regenerate the compiled-HTML golden used by `blocks-compile.test.ts`.
 *
 * Run after a deliberate change to an emitter, the shell or the default theme:
 *
 *   npx tsx scripts/regen-block-golden.mts
 *
 * Then read the diff. The golden exists so that an *un*intended change to the
 * compiled output — a padding tweak, a dropped attribute — fails a test instead
 * of shipping silently to a mailing list.
 */
import { writeFileSync } from "node:fs";
import { compile } from "../worker/src/lib/blocks/compile.ts";
import { BlockDocumentSchema } from "../worker/src/lib/blocks/schema.ts";
import { KITCHEN_SINK } from "../worker/src/__tests__/fixtures/kitchen-sink.ts";

const doc = BlockDocumentSchema.parse({ version: 1, blocks: KITCHEN_SINK });
const html = compile(doc, "Preheader text");

const banner = `// GENERATED by scripts/regen-block-golden.mts — do not edit by hand.
// Compiled output of the kitchen-sink fixture. A diff here is a change to what
// every block-authored campaign will mail; read it, don't just regenerate it.
`;

writeFileSync(
  new URL(
    "../worker/src/__tests__/fixtures/kitchen-sink.expected.ts",
    import.meta.url,
  ),
  `${banner}export const KITCHEN_SINK_HTML = ${JSON.stringify(html)};\n`,
);
console.log(`wrote golden: ${html.length} bytes`);
